2024-11-22 11:23:00,273 - root - WARNING - Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\Grigory3v\urban\git\URBAN\Python-разработчик\12.DevelopmentCycleSupport\04.pythonLogging\tests_12_4.py", line 25, in test_run
    test2 = rt_with_exceptions.Runner(5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Grigory3v\urban\git\URBAN\Python-разработчик\12.DevelopmentCycleSupport\04.pythonLogging\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-22 11:23:00,274 - root - WARNING - Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\Grigory3v\urban\git\URBAN\Python-разработчик\12.DevelopmentCycleSupport\04.pythonLogging\tests_12_4.py", line 15, in test_walk
    test1 = rt_with_exceptions.Runner("test1", -5)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Grigory3v\urban\git\URBAN\Python-разработчик\12.DevelopmentCycleSupport\04.pythonLogging\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
